-- Creates the `loan_products` table. Apply files in numeric order.
CREATE TABLE `loan_products` (
  `id` varchar(50) NOT NULL,
  `code` varchar(50) NOT NULL,
  `name` varchar(150) NOT NULL,
  `description` text,
  `version` int DEFAULT '1',
  `min_amount` decimal(15,2) NOT NULL,
  `max_amount` decimal(15,2) NOT NULL,
  `min_term_months` int DEFAULT NULL,
  `max_term_months` int DEFAULT NULL,
  `annual_interest_rate` decimal(5,2) NOT NULL,
  `default_term_months` int DEFAULT NULL,
  `interest_calculation_method` enum('Diminishing Balance','Flat Rate','Equal Amortization') NOT NULL,
  `payment_frequency` enum('Monthly','Semi-monthly','Weekly','Lump Sum') NOT NULL,
  `grace_period_days` int DEFAULT '0',
  `processing_fee_percentage` decimal(5,2) NOT NULL DEFAULT '0.00',
  `service_fee_fixed` decimal(12,2) NOT NULL DEFAULT '0.00',
  `penalty_rule_id` varchar(100) DEFAULT NULL,
  `collateral_required` tinyint(1) NOT NULL DEFAULT '0',
  `guarantor_required` tinyint(1) NOT NULL DEFAULT '0',
  `debit_account_id` varchar(100) DEFAULT NULL,
  `required_documents` json DEFAULT NULL,
  `approval_workflow_id` varchar(100) DEFAULT NULL,
  `effective_from` date DEFAULT NULL,
  `effective_until` date DEFAULT NULL,
  `penalty_rate_percentage` decimal(5,2) DEFAULT '2.00',
  `gl_receivable_account_id` varchar(50) NOT NULL,
  `gl_interest_income_account_id` varchar(50) NOT NULL,
  `active` tinyint(1) DEFAULT '1',
  PRIMARY KEY (`id`),
  UNIQUE KEY `code` (`code`),
  KEY `gl_receivable_account_id` (`gl_receivable_account_id`),
  KEY `gl_interest_income_account_id` (`gl_interest_income_account_id`),
  CONSTRAINT `loan_products_ibfk_1` FOREIGN KEY (`gl_receivable_account_id`) REFERENCES `chart_of_accounts` (`id`),
  CONSTRAINT `loan_products_ibfk_2` FOREIGN KEY (`gl_interest_income_account_id`) REFERENCES `chart_of_accounts` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
