-- Creates the `members` table. Apply files in numeric order.
CREATE TABLE `members` (
  `id` varchar(50) NOT NULL,
  `member_no` varchar(50) NOT NULL,
  `branch_id` varchar(50) NOT NULL,
  `member_type_id` varchar(50) NOT NULL,
  `first_name` varchar(100) NOT NULL,
  `last_name` varchar(100) NOT NULL,
  `middle_name` varchar(100) DEFAULT NULL,
  `gender` enum('Male','Female','Other') NOT NULL,
  `birthdate` date NOT NULL,
  `email` varchar(150) DEFAULT NULL,
  `phone` varchar(50) NOT NULL,
  `address` text NOT NULL,
  `status` enum('Active','Pending Approval','Inactive','Terminated','Deceased') DEFAULT 'Pending Approval',
  `joined_date` date NOT NULL,
  `custom_field_values` json DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `member_no` (`member_no`),
  KEY `branch_id` (`branch_id`),
  KEY `member_type_id` (`member_type_id`),
  KEY `idx_member_name` (`last_name`,`first_name`),
  KEY `idx_member_status` (`status`),
  CONSTRAINT `members_ibfk_1` FOREIGN KEY (`branch_id`) REFERENCES `branches` (`id`),
  CONSTRAINT `members_ibfk_2` FOREIGN KEY (`member_type_id`) REFERENCES `member_types` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
