-- Creates the `loans` table. Apply files in numeric order.
CREATE TABLE `loans` (
  `id` varchar(50) NOT NULL,
  `loan_account_no` varchar(50) NOT NULL,
  `application_id` varchar(50) DEFAULT NULL,
  `member_id` varchar(50) NOT NULL,
  `loan_product_id` varchar(50) NOT NULL,
  `product_version` int DEFAULT '1',
  `branch_id` varchar(50) NOT NULL,
  `principal_amount` decimal(15,2) NOT NULL,
  `annual_interest_rate` decimal(5,2) NOT NULL,
  `interest_calculation_method` varchar(50) NOT NULL,
  `term_months` int NOT NULL,
  `payment_frequency` varchar(50) NOT NULL,
  `disbursement_date` date NOT NULL,
  `first_due_date` date NOT NULL,
  `maturity_date` date NOT NULL,
  `processing_fee` decimal(15,2) DEFAULT '0.00',
  `service_fee` decimal(15,2) DEFAULT '0.00',
  `net_disbursed` decimal(15,2) NOT NULL,
  `disbursed_from_cash_account_id` varchar(50) NOT NULL,
  `status` enum('Draft','Submitted','Approved','Released','Active','Fully Paid','Past Due','Restructured','Pending') CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT 'Submitted',
  `current_balance` decimal(15,2) NOT NULL,
  `total_principal_paid` decimal(15,2) DEFAULT '0.00',
  `total_interest_paid` decimal(15,2) DEFAULT '0.00',
  `total_penalty_paid` decimal(15,2) DEFAULT '0.00',
  `total_fees_paid` decimal(15,2) DEFAULT '0.00',
  `approved_by` varchar(100) DEFAULT NULL,
  `approved_date` date DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `loan_account_no` (`loan_account_no`),
  KEY `loan_product_id` (`loan_product_id`),
  KEY `branch_id` (`branch_id`),
  KEY `disbursed_from_cash_account_id` (`disbursed_from_cash_account_id`),
  KEY `idx_loan_member` (`member_id`),
  KEY `idx_loan_status` (`status`),
  KEY `fk_loans_application` (`application_id`),
  CONSTRAINT `fk_loans_application` FOREIGN KEY (`application_id`) REFERENCES `loan_applications` (`id`),
  CONSTRAINT `loans_ibfk_1` FOREIGN KEY (`member_id`) REFERENCES `members` (`id`),
  CONSTRAINT `loans_ibfk_2` FOREIGN KEY (`loan_product_id`) REFERENCES `loan_products` (`id`),
  CONSTRAINT `loans_ibfk_3` FOREIGN KEY (`branch_id`) REFERENCES `branches` (`id`),
  CONSTRAINT `loans_ibfk_4` FOREIGN KEY (`disbursed_from_cash_account_id`) REFERENCES `cash_accounts` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
